version: "3"
services:
  back:
    build: ./back
    container_name: back
    ports:
      - "3305:3305"
    environment: 
      PORT : 3305
    healthcheck:
      test: curl --fail -s http://localhost:3305/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build: ./front
    container_name: front
    ports: 
      - "3306:3306"
    environment: 
      PORT : 3306
    healthcheck:
      test: curl --fail -s http://localhost:3306/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
